# https://docs.cortex.io/docs/reference/basics/entities#service-entities

openapi: 3.0.1
info:
  title: Azure Cli Credentials Proxy
  description: A containerized application that acts as a proxy, enabling other containerized applications to access Azure developer credentials without requiring the Azure CLI to be installed on each individual container.
  x-cortex-git:
    github:
      alias: gsoft-inc
      repository: gsoft-inc/azure-cli-credentials-proxy
  x-cortex-tag: service-azure-cli-credentials-proxy
  x-cortex-type: other
  x-cortex-slack:
    channels:
      - name: internal-dev-platform
        notificationsEnabled: true
  x-cortex-owners:
    - name: team-internal-developer-platform-backend
      type: GROUP
      provider: CORTEX
  x-cortex-link:
    - name: Documentation
      type: documentation
      url: https://gsoftdev.atlassian.net/wiki/spaces/TEC/pages/3557490915
    - type: cortex
      url: https://github.com/gsoft-inc/azure-cli-credentials-proxy/blob/main/.cortex/catalog/service-azure-cli-credentials-proxy.yaml
      name: Edit current Cortex entity in GitHub
