name: Publish

on:
  push:
    tags: ["*.*.*"]

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3
        with:
          username: ${{ secrets.WORKLEAP_DOCKERHUB_USERNAME }}
          password: ${{ secrets.WORKLEAP_DOCKERHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5
        with:
          images: workleap/azure-cli-credentials-proxy

      - name: Docker build and push
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  linearb-release:
    needs: [main]
    uses: gsoft-inc/wl-reusable-workflows/.github/workflows/linearb-deployment.yml@main
    with:
      environment: "release"
    secrets: inherit
